{
    "name": "Research Supply Chain",
    "version": "19.0.3.0.0",
    "category": "Research",
    "summary": "Manage research projects, researchers, requirements, resources, experiments, budgets, and outputs.",
    "author": "Research Supply Chain Team",
    "website": "https://github.com/AbdullahBahamish/Research-Supply-Chain",
    "depends": [
        "base",
        "web",
        "mail",
        "hr",
        "product",
        "analytic",
    ],
    "data": [
        "security/research_security.xml",
        "security/ir.model.access.csv",
        "data/research_supply_chain_data.xml",
        "data/ir_cron_data.xml",
        "data/mail_template_data.xml",
        "views/researcher_views.xml",
        "views/project_budget_views.xml",
        "views/research_requirement_views.xml",
        "views/research_resource_views.xml",
        "views/experiment_views.xml",
        "views/research_output_views.xml",
        "views/project_tag_views.xml",
        "views/research_paper_views.xml",
        "views/research_project_views.xml",
        "views/research_menu_root.xml",
        "views/research_tools_menu.xml",
        "views/sample_data_wizard_views.xml",
        "views/report_research_project.xml",
        "views/research_supply_chain_menus.xml",
    ],
    "demo": [
        "demo/research_supply_chain_demo.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "research_supply_chain/static/src/components/research_dashboard/research_dashboard.js",
            "research_supply_chain/static/src/components/research_dashboard/research_dashboard.xml",
            "research_supply_chain/static/src/components/research_dashboard/research_dashboard.scss",
            "research_supply_chain/static/src/components/budget_gauge/budget_gauge_widget.js",
            "research_supply_chain/static/src/components/budget_gauge/budget_gauge_widget.xml",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}